@baseUrl = http://localhost:9000/api

###
get {{baseUrl}}/users

###
post {{baseUrl}}/users
Content-Type: application/json

{
  "createUser": {
    "email": "danny@daniels.com",
    "password": "t00nie",
    "first_name": "Tony",
    "last_name": "Daniels",
    "username": "tdog21",
    "gender": "not sure",
    "avatar": "",
    "location": "London",
    "date_of_birth": "1999-12-31",
    "coding_languages": ["JavaScript", "TypeScript"],
    "interests": "Kung-Fu Panda",
    "host_ratings": 0
  }
}

###
get {{baseUrl}}/users/64ccb705ee5bbdb21111e35a

###
delete {{baseUrl}}/users/64cc9b357d09898985457d7d

###
get {{baseUrl}}/events

###
get {{baseUrl}}/events/64ccb705ee5bbdb21111e379

###
get {{baseUrl}}/events?topic=Innovation